apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: custom-mysql-storage
  hostPath:
    path: /mnt/data/custom-mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: custom-mysql-pvc
  namespace: custom-app-lab
spec:
  volumeName: custom-mysql-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-mysql-storage
  resources:
    requests:
      storage: 5Gi
